import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D

datos=np.genfromtxt("datos.txt")
x=np.linspace(0,1,100)
y=np.linspace(0,1,100)
x,y = np.meshgrid(x,y)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(x, y, datos, linewidth=0, antialiased=True, cmap=cm.coolwarm)
plt.title("Placa t=0s")
ax.set_zlabel("Temperatura [°C]")
ax.set_xlabel("x[m]")
ax.set_ylabel("y[m]")
plt.savefig("placatempt0.png")

datos=np.genfromtxt("datos2.txt")
x=np.linspace(0,1,100)
y=np.linspace(0,1,100)
x,y = np.meshgrid(x,y)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(x, y, datos, linewidth=0, antialiased=True, cmap=cm.coolwarm)
plt.title("Placa t=100s")
ax.set_zlabel("Temperatura [°C]")
ax.set_xlabel("x[m]")
ax.set_ylabel("y[m]")
plt.savefig("placatempt100.png")

datos=np.genfromtxt("datos3.txt")
x=np.linspace(0,1,100)
y=np.linspace(0,1,100)
x,y = np.meshgrid(x,y)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(x, y, datos, linewidth=0, antialiased=True, cmap=cm.coolwarm)
plt.title("Placa t=1000s")
ax.set_zlabel("Temperatura [°C]")
ax.set_xlabel("x[m]")
ax.set_ylabel("y[m]")
plt.savefig("placatempt1000.png")

datos=np.genfromtxt("datos4.txt")
x=np.linspace(0,1,100)
y=np.linspace(0,1,100)
x,y = np.meshgrid(x,y)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(x, y, datos, linewidth=0, antialiased=True, cmap=cm.coolwarm)
plt.title("Placa t=2500s")
ax.set_zlabel("Temperatura [°C]")
ax.set_xlabel("x[m]")
ax.set_ylabel("y[m]")
plt.savefig("placatempt2500.png")