#https://github.com/JuanOrmaza/MetodosComputacionales/tree/master/tarea2

import numpy as np
import matplotlib.pyplot as plt

#datos
datoseuler1=np.genfromtxt("datoseuler1.txt")
datoseuler2=np.genfromtxt("datoseuler2.txt")
datoseuler3=np.genfromtxt("datoseuler3.txt")
datosleap1=np.genfromtxt("datosleap1.txt")
datosleap2=np.genfromtxt("datosleap2.txt")
datosleap3=np.genfromtxt("datosleap3.txt")
datosrunge1=np.genfromtxt("datosrunge1.txt")
datosrunge2=np.genfromtxt("datosrunge2.txt")
datosrunge3=np.genfromtxt("datosrunge3.txt")

#grafica x vs y
plt.figure(figsize=(15,20))
plt.suptitle("y vs x", size=20)
plt.subplot(3,3,1)
plt.plot(datoseuler1[:,1],datoseuler1[:,3])
plt.title("euler con dt=0.1")
plt.xlabel('x [UA]')
plt.ylabel('y [UA]')
plt.subplot(3,3,2)
plt.plot(datoseuler2[:,1],datoseuler2[:,3])
plt.title("euler con dt=0.01")
plt.xlabel('x [UA]')
plt.ylabel('y [UA]')
plt.subplot(3,3,3)
plt.plot(datoseuler3[:,1],datoseuler3[:,3])
plt.title("euler con dt=0.001")
plt.xlabel('x [UA]')
plt.ylabel('y [UA]')
plt.subplot(3,3,4)
plt.plot(datosleap1[:,1],datosleap1[:,3])
plt.title("leapfrog con dt=0.1")
plt.xlabel('x [UA]')
plt.ylabel('y [UA]')
plt.subplot(3,3,5)
plt.plot(datosleap2[:,1],datosleap2[:,3])
plt.title("leapfrog con dt=0.01")
plt.xlabel('x [UA]')
plt.ylabel('y [UA]')
plt.subplot(3,3,6)
plt.plot(datosleap3[:,1],datosleap3[:,3])
plt.title("leapfrog con dt=0.001")
plt.xlabel('x [UA]')
plt.ylabel('y [UA]')
plt.subplot(3,3,7)
plt.plot(datosrunge1[:,1],datosrunge1[:,3])
plt.title("runge kutta 4orden con dt=0.1")
plt.xlabel('x [UA]')
plt.ylabel('y [UA]')
plt.subplot(3,3,8)
plt.plot(datosrunge2[:,1],datosrunge2[:,3])
plt.title("runge kutta 4orden con dt=0.01")
plt.xlabel('x [UA]')
plt.ylabel('y [UA]')
plt.subplot(3,3,9)
plt.plot(datosrunge3[:,1],datosrunge3[:,3])
plt.title("runge kutta 4orden con dt=0.001")
plt.xlabel('x [UA]')
plt.ylabel('y [UA]')
plt.savefig("XY_met_dt.pdf")

#grafica vx vs vy
plt.figure(figsize=(15,20))
plt.suptitle("Vy vs Vx",size=20)
plt.subplot(3,3,1)
plt.plot(datoseuler1[:,2],datoseuler1[:,4])
plt.title("euler con dt=0.1")
plt.xlabel('x [UA/year]')
plt.ylabel('y [UA/year]')
plt.subplot(3,3,2)
plt.plot(datoseuler2[:,2],datoseuler2[:,4])
plt.title("euler con dt=0.01")
plt.xlabel('x [UA/year]')
plt.ylabel('y [UA/year]')
plt.subplot(3,3,3)
plt.plot(datoseuler3[:,2],datoseuler3[:,4])
plt.title("euler con dt=0.001")
plt.xlabel('x [UA/year]')
plt.ylabel('y [UA/year]')
plt.subplot(3,3,4)
plt.plot(datosleap1[:,2],datosleap1[:,4])
plt.title("leapfrog con dt=0.1")
plt.xlabel('x [UA/year]')
plt.ylabel('y [UA/year]')
plt.subplot(3,3,5)
plt.plot(datosleap2[:,2],datosleap2[:,4])
plt.title("leapfrog con dt=0.01")
plt.xlabel('x [UA/year]')
plt.ylabel('y [UA/year]')
plt.subplot(3,3,6)
plt.plot(datosleap3[:,2],datosleap3[:,4])
plt.title("leapfrog con dt=0.001")
plt.xlabel('x [UA/year]')
plt.ylabel('y [UA/year]')
plt.subplot(3,3,7)
plt.plot(datosrunge1[:,2],datosrunge1[:,4])
plt.title("runge kutta 4orden con dt=0.1")
plt.xlabel('x [UA/year]')
plt.ylabel('y [UA/year]')
plt.subplot(3,3,8)
plt.plot(datosrunge2[:,2],datosrunge2[:,4])
plt.title("runge kutta 4orden con dt=0.01")
plt.xlabel('x [UA/year]')
plt.ylabel('y [UA/year]')
plt.subplot(3,3,9)
plt.plot(datosrunge3[:,2],datosrunge3[:,4])
plt.title("runge kutta 4orden con dt=0.001")
plt.xlabel('x [UA/year]')
plt.ylabel('y [UA/year]')
plt.savefig("VxVy_met_dt.pdf")


#energias
def energia(x,y,vx,vy):
    masa=3.00273e-6
    G=6.674*1e-11*(1/((1.496*1e11)**3))*1.989*1e30*(31536000**2)
    tam=len(x)
    ener=[]
    for i in range(tam):
        calculo=-G*masa*((x[i]**2+y[i]**2)**0.5)-(1/2)*masa*vx[i]**2-(1/2)*masa*vy[i]**2
        ener.append(calculo)
    return ener

                   
#moment angular
def momang(x,y,vx,vy):
    masa=3.00273e-6
    tam=len(x)
    mom=[]
    for i in range(tam):
        mom.append((masa*vx[i]+masa*vy[i])*((x[i]**2+y[i]**2)**0.5))
    return mom


#grafica momento
plt.figure(figsize=(25,25))
plt.suptitle("momento angular vs tiempo",size=20)
plt.subplot(3,3,1)
plt.plot(datoseuler1[:,0],momang(datoseuler1[:,1],datoseuler1[:,3],datoseuler1[:,2],datoseuler1[:,4]))
plt.title("mom. ang. euler con dt=0.1")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year]')
plt.subplot(3,3,2)
plt.plot(datoseuler2[:,0],momang(datoseuler2[:,1],datoseuler2[:,3],datoseuler2[:,2],datoseuler2[:,4]))
plt.title("mom. ang. euler con dt=0.01")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year]')
plt.subplot(3,3,3)
plt.plot(datoseuler3[:,0],momang(datoseuler3[:,1],datoseuler3[:,3],datoseuler3[:,2],datoseuler3[:,4]))
plt.title("mom. ang. euler con dt=0.001")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year]')
plt.subplot(3,3,4)
plt.plot(datosleap1[:,0],momang(datosleap1[:,1],datosleap1[:,3],datosleap1[:,2],datosleap1[:,4]))
plt.title("mom. ang. leapfrog con dt=0.1")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year]')
plt.subplot(3,3,5)
plt.plot(datosleap2[:,0],momang(datosleap2[:,1],datosleap2[:,3],datosleap2[:,2],datosleap2[:,4]))
plt.title("mom. ang. leapfrog con dt=0.01")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year]')
plt.subplot(3,3,6)
plt.plot(datosleap3[:,0],momang(datosleap3[:,1],datosleap3[:,3],datosleap3[:,2],datosleap3[:,4]))
plt.title("mom. ang. leapfrog con dt=0.001")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year]')
plt.subplot(3,3,7)
plt.plot(datosrunge1[:,0],momang(datosrunge1[:,1],datosrunge1[:,3],datosrunge1[:,2],datosrunge1[:,4]))
plt.title("mom. ang. rungekut con dt=0.1")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year]')
plt.subplot(3,3,8)
plt.plot(datosrunge2[:,0],momang(datosrunge2[:,1],datosrunge2[:,3],datosrunge2[:,2],datosrunge2[:,4]))
plt.title("mom. ang. rungekut con dt=0.01")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year]')
plt.subplot(3,3,9)
plt.plot(datosrunge3[:,0],momang(datosrunge3[:,1],datosrunge3[:,3],datosrunge3[:,2],datosrunge3[:,4]))
plt.title("mom. ang. rungekut con dt=0.001")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year]')
plt.savefig("Mome_met_dt.pdf")

#grafica energia
plt.figure(figsize=(25,25))
plt.suptitle("energia vs tiempo",size=20)
plt.subplot(3,3,1)
plt.plot(datoseuler1[:,0],energia(datoseuler1[:,1],datoseuler1[:,3],datoseuler1[:,2],datoseuler1[:,4]))
plt.title("energia euler con dt=0.1")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year^2]')
plt.subplot(3,3,2)
plt.plot(datoseuler2[:,0],energia(datoseuler2[:,1],datoseuler2[:,3],datoseuler2[:,2],datoseuler2[:,4]))
plt.title("energia euler con dt=0.01")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year^2]')
plt.subplot(3,3,3)
plt.plot(datoseuler3[:,0],energia(datoseuler3[:,1],datoseuler3[:,3],datoseuler3[:,2],datoseuler3[:,4]))
plt.title("energia euler con dt=0.001")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year^2]')
plt.subplot(3,3,4)
plt.plot(datosleap1[:,0],energia(datosleap1[:,1],datosleap1[:,3],datosleap1[:,2],datosleap1[:,4]))
plt.title("energia leapfrog con dt=0.1")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year^2]')
plt.subplot(3,3,5)
plt.plot(datosleap2[:,0],energia(datosleap2[:,1],datosleap2[:,3],datosleap2[:,2],datosleap2[:,4]))
plt.title("energia leapfrog con dt=0.01")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year^2]')
plt.subplot(3,3,6)
plt.plot(datosleap3[:,0],energia(datosleap3[:,1],datosleap3[:,3],datosleap3[:,2],datosleap3[:,4]))
plt.title("energia rungekut con dt=0.001")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year^2]')
plt.subplot(3,3,7)
plt.plot(datosrunge1[:,0],energia(datosrunge1[:,1],datosrunge1[:,3],datosrunge1[:,2],datosrunge1[:,4]))
plt.title("energia rungekut con dt=0.1")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year^2]')
plt.subplot(3,3,8)
plt.plot(datosrunge2[:,0],energia(datosrunge2[:,1],datosrunge2[:,3],datosrunge2[:,2],datosrunge2[:,4]))
plt.title("energia rungekut con dt=0.01")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year^2]')
plt.subplot(3,3,9)
plt.plot(datosrunge3[:,0],energia(datosrunge3[:,1],datosrunge3[:,3],datosrunge3[:,2],datosrunge3[:,4]))
plt.title("energia leapfrog con dt=0.001")
plt.xlabel('t [year]')
plt.ylabel('y [masasol*UA^2/year^2]')
plt.savefig("Ener_met_dt.pdf")


arch = open("Resultados_hw2.txt","w")
arch.write("Resultados parte 2:  Transformada de Fourier: Imagenes hibridas. \n")
arch.write("\n")
arch.write("Los pasos, presentados en las 3 graficas, consisten en convertir ambas imagenes al espacio de fourier. \n")
arch.write("Posterior a la conversion, se realiza una observacion de las frecuencias del espectro de fourier, esto con el proposito de generar un filtro. \n")
arch.write(" Los filtros utilizados consisten de un filtro pasa bajas y uno pasa altas. La suma de las transformadas de Fourier filtradas se llevan posteriormente a la normalidad con una transformada inversa. \n")
arch.write("Los resultados, como se pueden observar, fueron satisfactorios. \n")
arch.write("\n")
arch.write("Resultados parte 3: Comparacion de los distintos metodos de solucion de ecuaciones diferenciales ordinarias: caso de una masa orbitando alrededor de otra. \n")
arch.write("\n")
arch.write("posicionex x,y: \n")
arch.write("Se logro generar orbitas circulares concentricas para los 3 casos de ODEs. \n")
arch.write("Adicionalmente, se pudo observar que euler es el menos preciso pero mejora con un dt menor. \n")
arch.write("velocidades x,y: \n")
arch.write("Se logra observar circulos formados por las velociades en x y y. \n")
arch.write("Tambien se puede ver como estas velociades se ajustan a distintos cuadrantes, lo cual es esperado de los resultados. \n")
arch.write("Energia y momento angular xy,t: \n")
arch.write("Los resultados de la energia y momento angular son satisfactorios. Se logra visualizar como la energia y el momento se mantienen constantes. \n")
arch.write("Por otra parte, se observa para el metodo de euler y runge-kutta como al disminuir dt se mejora la conservacion de la energia y momento. \n")
arch.write("Esto se puede observar en el eje y con las magnitudes presentadas. \n")
arch.close()       








